In [1]:
import sys
sys.path.append('..')

import pandas as pd

from utils.db_utils import write_table, read_table, read_table

In [2]:
job_df = read_table("SELECT sector, subsector  FROM sc_bronze.dosm_jobdemand group by sector, subsector order by sector, subsector")
job_df.head(20)

                sector                                          subsector
0          Agriculture                                        Agriculture
1         Construction                                       Construction
2        Manufacturing          Electrical, electronic & optical products
3        Manufacturing      Food processing, beverages & tobacco products
4        Manufacturing  Non-metallic mineral products, basic metal & f...
5        Manufacturing     Petroleum, chemical, rubber & plastic products
6        Manufacturing       Textiles, wearing apparel & leather products
7        Manufacturing  Transport equipment, other manufacturing & repair
8        Manufacturing  Wood products, furniture, paper products & pri...
9   Mining & Quarrying                                 Mining & Quarrying
10            Services  Finance, insurance, real estate & business ser...
11            Services                 Food & beverages and accommodation
12            Services                        Information & communication
13            Services                                     Other services
14            Services                           Transportation & storage
15            Services                           Wholesale & retail trade

In [ ]:
import pandas as pd

URL_DATA = 'https://storage.dosm.gov.my/gdp/gdp_qtr_real_supply_sub.parquet'

df = pd.read_parquet(URL_DATA)

df

          series       date  sector     value
0            abs 2015-01-01      p0  282255.0
1            abs 2015-01-01      p1   21691.0
2            abs 2015-01-01    p1.1   13669.0
3            abs 2015-01-01  p1.1.1     993.0
4            abs 2015-01-01  p1.1.2    7278.0
...          ...        ...     ...       ...
9774  growth_qoq 2025-10-01  p5.4.1       4.8
9775  growth_qoq 2025-10-01  p5.4.2       0.9
9776  growth_qoq 2025-10-01  p5.4.6       0.8
9777  growth_qoq 2025-10-01    p5.5       9.3
9778  growth_qoq 2025-10-01      p6       3.9

[9779 rows x 4 columns]

In [2]:
URL_DATA = 'https://storage.dosm.gov.my/gdp/gdp_lookup.parquet'
look_up = pd.read_parquet(URL_DATA)

look_up

,method,code,desc_en,desc_bm
0,production,p0,GDP at purchasers' prices,KDNK pada harga pembeli
1,production,p1,Agriculture,Pertanian
2,production,p1.1,Crops,Tanaman
3,production,p1.1.1,Rubber,Getah
4,production,p1.1.2,Oil palm,Kelapa sawit
...,...,...,...,...
169,income,i1,Compensation of employees,Pampasan pekerja
170,income,i2,Gross operating surplus,Lebihan kendalian kasar
171,income,i3,Taxes less subsidies on production and imports,Cukai tolak subsidi ke atas pengeluaran dan im...
172,income,i3.1,Taxes on production and imports,Cukai ke atas pengeluaran dan import
173,income,i3.2,(less) subsidies,(tolak) subsidi