In [1]:
import sys
sys.path.append('../..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [2]:
df = read_table(
    """
    select distinct(underemp_type)
    from sc_bronze.dosm_underemployment
    """
)
df

  underemp_type
0          time
1         skill

In [4]:
df = df.sort_values("underemp_type").reset_index(drop=True)
df["underemp_type_id"] = ["UT" + str(i+1).zfill(3) for i in range(len(df))]
df = df[["underemp_type_id"] + [c for c in df.columns if c != "underemp_type_id"]]
df

  underemp_type_id underemp_type
0            UT001         skill
1            UT002          time

In [5]:
write_table(df, "sc_gold", "dim_underemp_type")

Table sc_gold.dim_underemp_type written successfully.