In [9]:
import sys
sys.path.append('../..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [10]:
df = read_table(
    """ select distinct skill_level from sc_bronze.dosm_emp_graduates_skill"""
)
df.head()

    skill_level
0   Low-skilled
1       Skilled
2  Semi-skilled

In [11]:
df = df.sort_values("skill_level").reset_index(drop=True)
df["skill_level_id"] = ["SL" + str(i+1).zfill(3) for i in range(len(df))]
df = df[["skill_level_id"] + [c for c in df.columns if c != "skill_level_id"]]
df

  skill_level_id   skill_level
0          SL001   Low-skilled
1          SL002  Semi-skilled
2          SL003       Skilled

In [12]:
write_table(df, "sc_gold", "dim_skilllevel")

Table sc_gold.dim_skilllevel written successfully.