In [4]:
import sys
sys.path.append('../..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [5]:
date = read_table("select * from sc_gold.dim_date")
sector= read_table("select * from sc_gold.dim_sector")

In [6]:
df = read_table("select * from sc_silver.forecast_supply_demand")
df

,date,sector,demand_pct,supply_pct,gap_pct,legend
0,2018-01-01,Agriculture,5.604762,1.414157,4.190605,historical
1,2018-01-01,Construction,15.530598,5.319443,10.211155,historical
2,2018-01-01,Manufacturing,26.170906,12.473264,13.697642,historical
3,2018-01-01,Mining and Quarrying,0.967193,1.051810,-0.084617,historical
4,2018-01-01,Services,51.726541,79.741325,-28.014785,historical
...,...,...,...,...,...,...
255,2030-10-01,Agriculture,NaN,NaN,5.631523,forecast
256,2030-10-01,Construction,NaN,NaN,6.833938,forecast
257,2030-10-01,Manufacturing,NaN,NaN,14.932956,forecast
258,2030-10-01,Mining and Quarrying,NaN,NaN,-0.104986,forecast
259,2030-10-01,Services,NaN,NaN,-28.441644,forecast

In [7]:
df = df.merge(
    date[["date", "date_id"]],
    on="date",
    how="left"
)

df = df.merge(
    sector[["sector", "sector_id"]],
    on="sector",
    how="left"
)

df_final = df.drop(columns=["date", "sector"])
id_cols = ["date_id", "sector_id"]
df_final = df_final[id_cols + [col for col in df_final.columns if col not in id_cols]]

In [8]:
df_final["sp_id"] = ["SP" + str(i+1).zfill(4) for i in range(len(df_final))]
df_final = df_final[["sp_id"] + [c for c in df_final.columns if c != "sp_id"]]
df_final

      sp_id date_id sector_id  demand_pct  supply_pct    gap_pct      legend
0    SP0001   DT009    SEC001    5.604762    1.414157   4.190605  historical
1    SP0002   DT009    SEC002   15.530598    5.319443  10.211155  historical
2    SP0003   DT009    SEC003   26.170906   12.473264  13.697642  historical
3    SP0004   DT009    SEC004    0.967193    1.051810  -0.084617  historical
4    SP0005   DT009    SEC005   51.726541   79.741325 -28.014785  historical
..      ...     ...       ...         ...         ...        ...         ...
255  SP0256   DT060    SEC001         NaN         NaN   5.631523    forecast
256  SP0257   DT060    SEC002         NaN         NaN   6.833938    forecast
257  SP0258   DT060    SEC003         NaN         NaN  14.932956    forecast
258  SP0259   DT060    SEC004         NaN         NaN  -0.104986    forecast
259  SP0260   DT060    SEC005         NaN         NaN -28.441644    forecast

[260 rows x 7 columns]

In [9]:
write_table(df_final, "sc_gold", "fact_supply_demand")

Table sc_gold.fact_supply_demand written successfully.