In [29]:
import sys
sys.path.append('../..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [30]:
date = read_table("select * from sc_gold.dim_date")
sector= read_table("select * from sc_gold.dim_sector")

In [31]:
df = read_table(
    """
    select 
    a.year,
    a.sector,
    a.total_emp_graduate,
    b.mean_salary_rm
    from sc_bronze.dosm_emp_graduates_sector a
    left join sc_bronze.dosm_mean_salary_sector b
    on a.year = b.year and a.sector = b.sector  
    """
)
df["date"] = pd.to_datetime(df["year"], format="%Y")
df.head()

   year                sector  total_emp_graduate  mean_salary_rm       date
0  2016           Agriculture             42500.0          3374.0 2016-01-01
1  2016          Construction            202500.0          4162.0 2016-01-01
2  2016         Manufacturing            424800.0          3935.0 2016-01-01
3  2016  Mining and Quarrying             48600.0          6777.0 2016-01-01
4  2016              Services           2758500.0          4363.0 2016-01-01

In [32]:
df = df.merge(
    date[["date", "date_id"]],
    on="date",
    how="left"
)

df = df.merge(
    sector[["sector", "sector_id"]],
    on="sector",
    how="left"
)

df_final = df.drop(columns=["year", "date", "sector"])
id_cols = ["date_id", "sector_id"]
df_final = df_final[id_cols + [col for col in df_final.columns if col not in id_cols]]

In [33]:
df_final["dsec_id"] = ["DSEC" + str(i+1).zfill(4) for i in range(len(df_final))]
df_final = df_final[["dsec_id"] + [c for c in df_final.columns if c != "dsec_id"]]
df_final

     dsec_id date_id sector_id  total_emp_graduate  mean_salary_rm
0   DSEC0001   DT001    SEC001             42500.0          3374.0
1   DSEC0002   DT001    SEC002            202500.0          4162.0
2   DSEC0003   DT001    SEC003            424800.0          3935.0
3   DSEC0004   DT001    SEC004             48600.0          6777.0
4   DSEC0005   DT001    SEC005           2758500.0          4363.0
5   DSEC0006   DT005    SEC001             46200.0          3770.0
6   DSEC0007   DT005    SEC002            219800.0          4268.0
7   DSEC0008   DT005    SEC003            486800.0          4019.0
8   DSEC0009   DT005    SEC004             39900.0          9757.0
9   DSEC0010   DT005    SEC005           2887300.0          4751.0
10  DSEC0011   DT009    SEC001             56200.0          4135.0
11  DSEC0012   DT009    SEC002            211400.0          4976.0
12  DSEC0013   DT009    SEC003            495700.0          4115.0
13  DSEC0014   DT009    SEC004             41800.0          9137.0
14  DSEC0015   DT009    SEC005           3169000.0          4965.0
15  DSEC0016   DT013    SEC001             57600.0          4143.0
16  DSEC0017   DT013    SEC002            226100.0          5014.0
17  DSEC0018   DT013    SEC003            538600.0          4612.0
18  DSEC0019   DT013    SEC004             43200.0          9011.0
19  DSEC0020   DT013    SEC005           3381200.0          5147.0
20  DSEC0021   DT017    SEC001             63800.0          3264.0
21  DSEC0022   DT017    SEC002            237400.0          4028.0
22  DSEC0023   DT017    SEC003            579400.0          3942.0
23  DSEC0024   DT017    SEC004             41400.0          6978.0
24  DSEC0025   DT017    SEC005           3131000.0          4763.0
25  DSEC0026   DT021    SEC001             56700.0          3325.0
26  DSEC0027   DT021    SEC002            257800.0          4267.0
27  DSEC0028   DT021    SEC003            574500.0          4151.0
28  DSEC0029   DT021    SEC004             39200.0          7236.0
29  DSEC0030   DT021    SEC005           3350400.0          4807.0
30  DSEC0031   DT025    SEC001             79000.0          3359.0
31  DSEC0032   DT025    SEC002            283100.0          4311.0
32  DSEC0033   DT025    SEC003            630400.0          4221.0
33  DSEC0034   DT025    SEC004             44200.0          7654.0
34  DSEC0035   DT025    SEC005           3497700.0          5033.0
35  DSEC0036   DT029    SEC001             83000.0          3435.0
36  DSEC0037   DT029    SEC002            301100.0          4534.0
37  DSEC0038   DT029    SEC003            637900.0          4437.0
38  DSEC0039   DT029    SEC004             46800.0          7675.0
39  DSEC0040   DT029    SEC005           3687000.0          5384.0
40  DSEC0041   DT033    SEC001             83900.0          3526.3
41  DSEC0042   DT033    SEC002            313100.0          4648.3
42  DSEC0043   DT033    SEC003            667300.0          4620.1
43  DSEC0044   DT033    SEC004             49200.0          8189.1
44  DSEC0045   DT033    SEC005           3863200.0          5487.4

In [34]:
write_table(df_final, "sc_gold", "fact_date_sector")

Table sc_gold.fact_date_sector written successfully.